version: "3.9"
services:
  db:
    container_name: postgres_container
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_MULTIPLE_DATABASES: mono-cinema, keycloak
    ports:
      - 5432:5432
    networks:
      - sso-simulation-network
    volumes:
      - db:/var/lib/postgresql/data
      - init_db:/docker-entrypoint-initdb.d
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "5050:80"
  keycloak:
    container_name: keycloak_postgres
    restart: unless-stopped
    tty: true
    command: ["start-dev", "--http-port", "8080", "--features=declarative-user-profile"]
    image: quay.io/keycloak/keycloak:17.0.1
    ports: 
      - "8080:8080"
    depends_on:
      - db
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASS}
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=root
    networks:
      - sso-simulation-network
networks:
  sso-simulation-network:
    name: sso-simulation-network
volumes:
  db:
    driver: local
  init_db:
    driver: local